### PR TITLE
Redirect to new profile path after sign up and show a message

### LINKED ISSUE #44: Not Obvious that User needs a Profile
# Description
Profiles are manually created by the user. They track events and friendships. This will eventually allow users to create separate profiles for work, close friends, and acquaintances.

Unfortunately, it's not obvious to first-time users that they need one to attend events. Let's auto-create or direct them to create one from error messages.

### PR DESCRIPTION
**Pull request by varkum**
## Description of Feature or Issue
closes #44 

User is redirected to the new profile path after sign up and asked to create a profile in the welcome message. I think this makes the most sense in terms of the registration flow, instead of waiting for an error message or auto-filling the profile. Had to create a new registrations controller to change the redirect path for Devise.

## Checklist
- [ ] Added/changed specs for the changes made
- [x] Is the linting build successful?
- [x] Is the test build successful?

## User-Facing Changes

Screenshot 2024-01-15 at 11 50 03 AM

### CODE REVIEW

**Review by ChaelCodes — APPROVED** [review]
This looks great, and I think this is a huge improvement for onboarding! Thank you so much for your contribution!

**Comment by varkum** [comment]
@ChaelCodes I was wondering if this project is still being actively developed? It's been a couple years since most of the issues were opened and was curious if it's back to being active?

**Comment by ChaelCodes** [comment]
Thanks for asking! It is active! I tried to deploy it on [stream](https://twitch.tv/ChaelCodes) today. I took a break for over a year because I was on maternity leave. Deployment didn't go so great this time due to some issues on fly.io's side, and it was previously deployed on Heroku, but when they changed their pricing tiers, they deleted my database, so I'm looking for a new more trustworthy hosting provider.

**Comment by ChaelCodes** [comment]
I'm currently in the process of renaming it from ConfBuddies to HallwayTrack or HallwayTracks. HallwayTrack is a really nice name, but there are people squatting on .com, .io, and .xyz, and HallwayTracks is clear.

**Comment by varkum** [comment]
You could try using Kamal and Digital Ocean/Hetzner! Found it to be a really simple and cheap way to deploy

**Pull request merged**
